language: python
python:
  - "2.7"
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get install -qq python-numpy python-scipy
install:
  - pip install -r requirements.txt --use-mirrors
before_script:
  - mysql -e 'create database sprks;'
script:
  - py.test
notifications:
  email: false
